### ISSUE TITLE
Error in conver_to_tf_records

### ISSUE THREAD

**Issue by bestspyever** [bendidi/X-ray-classification#2]
Hi! I try to run this file and I'm getting error: 

>> Converting image 1/2711 shard 0Traceback (most recent call last):
  File "convert_to_tf_records.py", line 66, in <module>
    main()
  File "convert_to_tf_records.py", line 57, in main
    _convert_dataset('train', training_filenames, training_labels, dataset_file = FLAGS.dataset_file,tfrecord_filename = FLAGS.tfrecord_filename,_NUM_SHARDS = FLAGS.num_shards)
  File "D:\X-ray-classification-master\X-ray-classification-master\data\dataset_utils.py", line 165, in _convert_dataset
    image_data = tf.gfile.FastGFile(filenames[i], 'r').read()
  File "C:\Users\S\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 125, in read
    pywrap_tensorflow.ReadFromStream(self._read_buf, length, status))
  File "C:\Users\S\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 93, in _prepare_value
    return compat.as_str_any(val)
  File "C:\Users\S\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\util\compat.py", line 106, in as_str_any
    return as_str(value)
  File "C:\Users\S\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\util\compat.py", line 84, in as_text
    return bytes_or_text.decode(encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte

**Comment by bestspyever** [comment]
Changed this string in dataset_utils.py

`            # Read the filename:
            image_data = tf.gfile.FastGFile(filenames[i], 'r').read()`

on 

`            # Read the filename:
            image_data = tf.gfile.FastGFile(filenames[i], 'rb').read()`
